-- DEMO reference data (is_demo = true). Simplified; not a complete reproduction of the care insurance system.

insert into public.care_services (code, name, category, description) values
  ('S001', '訪問介護', 'home_visit', '訪問介護員が自宅を訪問し、入浴・排泄・食事等の介助や生活援助を行う。'),
  ('S002', '訪問入浴介護', 'home_visit', '浴槽を積んだ車などで自宅を訪問し、入浴の介助を行う。'),
  ('S003', '訪問看護', 'home_visit', '看護師等が自宅を訪問し、療養上の世話や診療の補助を行う。'),
  ('S004', '訪問リハビリテーション', 'home_visit', '理学療法士等が自宅を訪問し、リハビリテーションを行う。'),
  ('S005', '通所介護', 'day_service', 'デイサービス。日中に施設へ通い、入浴・食事・機能訓練等を受ける。'),
  ('S006', '通所リハビリテーション', 'day_service', 'デイケア。施設へ通い、リハビリテーションを受ける。'),
  ('S007', '短期入所生活介護', 'short_stay', 'ショートステイ。短期間施設に宿泊し、介護を受ける。家族の負担軽減にも使われる。'),
  ('S008', '小規模多機能型居宅介護', 'community_multi', '通い・訪問・泊まりを一つの事業所で組み合わせて利用する地域密着型サービス。'),
  ('S009', '定期巡回・随時対応型訪問介護看護', 'home_visit', '日中・夜間を通じて定期巡回と随時の対応を行う地域密着型サービス。'),
  ('S010', '認知症対応型共同生活介護', 'residential', 'グループホーム。認知症の方が少人数で共同生活を送る地域密着型サービス。'),
  ('S011', '介護老人福祉施設', 'residential', '特別養護老人ホーム。常時介護が必要な方の生活施設。'),
  ('S012', '介護老人保健施設', 'residential', '在宅復帰を目指してリハビリ等を行う施設。'),
  ('S013', '介護医療院', 'residential', '長期的な医療と介護が必要な方のための施設。');

insert into public.care_actions (code, name, action_type, description) values
  ('A001', '要介護認定の申請', 'application', '介護保険サービスを利用するために、市区町村へ要介護（要支援）認定を申請する。'),
  ('A002', '地域包括支援センターへの相談', 'consultation', '高齢者の総合相談窓口。介護・福祉・医療の相談やサービス利用の入口になる。'),
  ('A003', 'ケアマネジャーへの相談', 'consultation', '担当ケアマネジャー（居宅介護支援事業所）にケアプランの見直し等を相談する。');

insert into public.source_service_concepts (dataset_code, concept_code, concept_label, notes) values
  ('K25', 'visit', '訪問系', '国民生活基礎調査の広いサービス区分（デモ）'),
  ('K25', 'day', '通所系', '国民生活基礎調査の広いサービス区分（デモ）'),
  ('K25', 'short_stay', '短期入所系', '国民生活基礎調査の広いサービス区分（デモ）'),
  ('K25', 'multi', '小規模多機能型等', '国民生活基礎調査の広いサービス区分（デモ）'),
  ('C26', 'home_help', '訪問介護', '介護給付費等実態統計のサービス種類（デモ）'),
  ('C26', 'home_nursing', '訪問看護', '介護給付費等実態統計のサービス種類（デモ）'),
  ('C26', 'day_care', '通所介護', '介護給付費等実態統計のサービス種類（デモ）'),
  ('C26', 'small_multi', '小規模多機能型居宅介護', '介護給付費等実態統計のサービス種類（デモ）'),
  ('P26', '110', '訪問介護', '介護サービス情報公表システムのサービス種別コード'),
  ('P26', '120', '訪問入浴介護', '介護サービス情報公表システムのサービス種別コード'),
  ('P26', '130', '訪問看護', '介護サービス情報公表システムのサービス種別コード'),
  ('P26', '140', '訪問リハビリテーション', '介護サービス情報公表システムのサービス種別コード'),
  ('P26', '150', '通所介護', '介護サービス情報公表システムのサービス種別コード'),
  ('P26', '160', '通所リハビリテーション', '介護サービス情報公表システムのサービス種別コード'),
  ('P26', '320', '認知症対応型共同生活介護', '介護サービス情報公表システムのサービス種別コード'),
  ('P26', '510', '介護老人福祉施設', '介護サービス情報公表システムのサービス種別コード'),
  ('P26', '520', '介護老人保健施設', '介護サービス情報公表システムのサービス種別コード'),
  ('P26', '550', '介護医療院', '介護サービス情報公表システムのサービス種別コード'),
  ('P26', '730', '小規模多機能型居宅介護', '介護サービス情報公表システムのサービス種別コード'),
  ('P26', '760', '定期巡回・随時対応型訪問介護看護', '介護サービス情報公表システムのサービス種別コード'),
  ('S22', 'tokuyo', '介護老人福祉施設', '施設・事業所調査の施設種類（デモ）'),
  ('S22', 'roken', '介護老人保健施設', '施設・事業所調査の施設種類（デモ）'),
  ('S22', 'iryoin', '介護医療院', '施設・事業所調査の施設種類（デモ）');

insert into public.service_mappings (source_concept_id, service_code, relation)
select c.id, m.service_code, m.relation
from (values
  ('K25', 'visit', 'S001', 'broader_than'),
  ('K25', 'visit', 'S002', 'broader_than'),
  ('K25', 'visit', 'S003', 'broader_than'),
  ('K25', 'visit', 'S004', 'broader_than'),
  ('K25', 'visit', 'S009', 'broader_than'),
  ('K25', 'day', 'S005', 'broader_than'),
  ('K25', 'day', 'S006', 'broader_than'),
  ('K25', 'short_stay', 'S007', 'broader_than'),
  ('K25', 'multi', 'S008', 'broader_than'),
  ('C26', 'home_help', 'S001', 'exact_match'),
  ('C26', 'home_nursing', 'S003', 'exact_match'),
  ('C26', 'day_care', 'S005', 'exact_match'),
  ('C26', 'small_multi', 'S008', 'exact_match'),
  ('P26', '110', 'S001', 'exact_match'),
  ('P26', '120', 'S002', 'exact_match'),
  ('P26', '130', 'S003', 'exact_match'),
  ('P26', '140', 'S004', 'exact_match'),
  ('P26', '150', 'S005', 'exact_match'),
  ('P26', '160', 'S006', 'exact_match'),
  ('P26', '320', 'S010', 'exact_match'),
  ('P26', '510', 'S011', 'exact_match'),
  ('P26', '520', 'S012', 'exact_match'),
  ('P26', '550', 'S013', 'exact_match'),
  ('P26', '730', 'S008', 'exact_match'),
  ('P26', '760', 'S009', 'exact_match'),
  ('S22', 'tokuyo', 'S011', 'exact_match'),
  ('S22', 'roken', 'S012', 'exact_match'),
  ('S22', 'iryoin', 'S013', 'exact_match')
) as m (dataset_code, concept_code, service_code, relation)
join public.source_service_concepts c on c.dataset_code = m.dataset_code and c.concept_code = m.concept_code;

-- Demo eligibility rules. care_level ordinal: 要支援1=0.1, 要支援2=0.2, 要介護1..5 = 1..5.
insert into public.eligibility_rules (rule_id, target_service_code, target_action_code, condition, effect, explanation, source, caveat) values
  ('R001', null, 'A001', '{"certification_status_in": ["not_applied", "applying", "unknown"]}', 'recommend_action',
   '介護保険サービスの利用には、要介護（要支援）認定が必要です。', 'デモ用簡略ルール（介護保険制度の一般的な仕組みを簡略化）',
   '実際の制度条件を完全に再現していません。申請方法は自治体公式情報を確認してください。'),
  ('R002', 'S011', null, '{"care_level_below": 3}', 'not_eligible_in_principle',
   '介護老人福祉施設（特別養護老人ホーム）は、原則として要介護3以上の方が対象です（特例入所の仕組みがあります）。', 'デモ用簡略ルール',
   '実際の制度条件を完全に再現していません。特例入所の可否は自治体・施設に確認してください。'),
  ('R003', 'S012', null, '{"care_level_below": 1}', 'not_eligible_in_principle',
   '介護老人保健施設は、要介護1以上の方が対象です。', 'デモ用簡略ルール',
   '実際の制度条件を完全に再現していません。'),
  ('R004', 'S013', null, '{"care_level_below": 1}', 'not_eligible_in_principle',
   '介護医療院は、要介護1以上で長期的な医療ケアが必要な方が主な対象です。', 'デモ用簡略ルール',
   '実際の制度条件を完全に再現していません。'),
  ('R005', 'S010', null, '{"always": true}', 'requires_check',
   '認知症対応型共同生活介護は、認知症の診断があり、原則として事業所と同じ市町村に住民票がある方が対象の地域密着型サービスです。', 'デモ用簡略ルール',
   '実際の制度条件を完全に再現していません。要支援1の方は利用できない等の条件もあります。'),
  ('R006', 'S008', null, '{"always": true}', 'requires_check',
   '小規模多機能型居宅介護は地域密着型サービスで、原則として事業所と同じ市町村に住む方が対象です。', 'デモ用簡略ルール',
   '実際の制度条件を完全に再現していません。'),
  ('R007', 'S009', null, '{"care_level_below": 1}', 'not_eligible_in_principle',
   '定期巡回・随時対応型訪問介護看護は、要介護1以上の方が対象の地域密着型サービスです。', 'デモ用簡略ルール',
   '実際の制度条件を完全に再現していません。');

insert into public.need_service_mappings (need_code, need_label, service_code, action_code, strength, rationale) values
  ('bathing_support', '入浴の支援', 'S002', null, 'primary', '自宅で浴槽を持ち込み、専門スタッフが入浴を介助する。'),
  ('bathing_support', '入浴の支援', 'S001', null, 'primary', '自宅の浴室での入浴介助を訪問介護で受けられる場合がある。'),
  ('bathing_support', '入浴の支援', 'S005', null, 'primary', '通所先の浴室で入浴支援を受けられる。'),
  ('bathing_support', '入浴の支援', 'S008', null, 'secondary', '通い・訪問の中で入浴支援を組み合わせられる。'),
  ('bathing_support', '入浴の支援', 'S006', null, 'secondary', '通所リハビリで入浴支援がある場合がある。'),
  ('daytime_supervision', '日中の見守り・独居時間の長さ', 'S005', null, 'primary', '日中を通所先で過ごすことで一人の時間を減らせる。'),
  ('daytime_supervision', '日中の見守り・独居時間の長さ', 'S008', null, 'primary', '通い・訪問・泊まりを柔軟に組み合わせられる。'),
  ('daytime_supervision', '日中の見守り・独居時間の長さ', 'S009', null, 'secondary', '定期巡回と随時対応で在宅時の安否確認を補える。'),
  ('daytime_supervision', '日中の見守り・独居時間の長さ', 'S001', null, 'secondary', '訪問時の様子確認を含めて生活を支える。'),
  ('medication_support', '服薬管理の支援', 'S001', null, 'primary', '訪問時に服薬の声かけ・確認を行える場合がある。'),
  ('medication_support', '服薬管理の支援', 'S003', null, 'primary', '看護師が服薬管理や体調確認を行う。'),
  ('medication_support', '服薬管理の支援', 'S009', null, 'secondary', '定期的な訪問で服薬確認を補える。'),
  ('family_respite', '家族の介護負担の軽減', 'S007', null, 'primary', '短期間の宿泊で家族の負担を軽減できる。'),
  ('family_respite', '家族の介護負担の軽減', 'S005', null, 'secondary', '日中のサービス利用で家族の時間を確保できる。'),
  ('home_living', '自宅での生活継続', 'S001', null, 'primary', '自宅での生活を続けながら必要な介助を受けられる。'),
  ('home_living', '自宅での生活継続', 'S008', null, 'primary', '住み慣れた地域・自宅での生活を支える複合型サービス。'),
  ('home_living', '自宅での生活継続', 'S009', null, 'secondary', '在宅生活を24時間の巡回・随時対応で支える。'),
  ('dementia_care', '認知症への支援', 'S008', null, 'secondary', 'なじみのスタッフによる継続的な関わりが得られる。'),
  ('dementia_care', '認知症への支援', 'S010', null, 'secondary', '認知症の方向けの共同生活。住み替えを伴う。'),
  ('rehabilitation', '身体機能の維持・リハビリ', 'S004', null, 'primary', '自宅でリハビリを受けられる。'),
  ('rehabilitation', '身体機能の維持・リハビリ', 'S006', null, 'primary', '通所でリハビリを受けられる。'),
  ('certification_needed', '要介護認定が必要', null, 'A001', 'primary', '介護保険サービス利用の前提となる。'),
  ('consultation_entry', 'どこに相談すべきか分からない', null, 'A002', 'primary', '地域の総合相談窓口として最初の相談先になる。'),
  ('care_plan_review', 'ケアプランの見直し', null, 'A003', 'primary', '利用中のサービスの見直しはケアマネジャーが窓口になる。');
